### ISSUE TITLE
Having"deferred" on listen directive is advisable?

### ISSUE THREAD

**Issue by RoldanLT** [h5bp/server-configs-nginx#100]
listen 80 deferred;

What is the advantages of having it and what is the disadvantage?
Please enlighten me  :)

**Comment by pentago** [comment]
Let me Google that for you.. 

"TCP_DEFER_ACCEPT can help boost performance by reducing the amount of preliminary formalities that happen between the server and client."

**Comment by RoldanLT** [comment]
I've read that many times.
But looks like not official answer from Nginx Devs.

**Comment by pentago** [comment]
I don't think that's their job.. 

Nginx just take advantage of that feature which is Linux native. I guess this is the wrong place to get in-depth knowledge about this OS specific feature. 

As a side note: http://www.techrepublic.com/article/take-advantage-of-tcp-ip-options-to-optimize-data-transmission/

**Comment by AD7six** [comment]
I don't think it's unreasonable for [the listen directives](https://github.com/h5bp/server-configs-nginx/blob/master/sites-available/example.com#L18-L21) to be explained.

**Comment by RoldanLT** [comment]
OK, I will enable it on my CentOS 6.6 64bit Server, in port 80 and 443 :).
Thanks!

**Comment by pentago** [comment]
I think TR artcle above could help understanding this matter a bit better..

**Comment by RoldanLT** [comment]
Yes, lots of info to read.

**Comment by CMCDragonkai** [comment]
On an IPv6 virtual machine, having `deferred` on both IPv6 and IPv4 listen directives results in a duplicate ` duplicate listen options for [::]:80`. This didn't happen until I got an IPv6 machine.

**Comment by AD7six** [comment]
Closing as I think the discussion here was all that the OP wanted.
