### ISSUE TITLE
nginx absolute paths

### ISSUE THREAD

**Issue by designermonkey** [h5bp/server-configs-nginx#101]
Hello.

I just read on the nginx site:

>nginx uses absolute paths only, all relative paths in configuration files are relative to --prefix==PATH.

Sadly the prefix path is usually `/usr/share/nginx` on ubuntu systems (not sure about others), and not the config path. This explains why I can't include any h5bp configs properly :(

Could the paths be changed to absolute paths? Specifically the `basic.conf`?

**Comment by AD7six** [comment]
> Could the paths be changed to absolute paths? Specifically the basic.conf?

That would fix it for some and break it for others - I don't see a good solution to what you ask except to make the files install specific.

> Sadly the prefix path is usually /usr/share/nginx on ubuntu system

Funnily enough I use ubuntu - and have never had a problem :P

**Comment by designermonkey** [comment]
Yeah, it's weird, it works fine this time, but on another server it didn't.

**Comment by rinatio** [comment]
Having same issue on debian-jessie. Is there any way to change nginx prefix path?

**Comment by designermonkey** [comment]
try `nginx --help` to see the options, I know it is an option.

**Comment by rinatio** [comment]
Yes, `nginx -h` says there's a `-p` option and it would work if you always run it manually

Is there some way to change the default one (other than recompiling) via some config file maybe? Maybe it's possible to do for `/etc/init.d/nginx` at least?

I already set absolute paths for the logs so I'm just curious, `include` option works relative to `/etc/nginx` for me.

**Comment by rinatio** [comment]
@AD7six Would you mind to add some note to the `gettings-started.md` documentation about this specific issue? Half year later I faced it again on another project and couldn't figure out why nginx keep saying

```
nginx: [emerg] open() "/usr/share/nginx/logs/error.log" failed (2: No such file or directory)
```
even though I added /etc/nginx/logs symlink by the docs until rememeber this case.

It's the same `/usr/share/nginx` on latest Ubuntu LTS and Debian as far as I know. And it's default to `/usr/local/nginx`in [nginx itself](https://www.nginx.com/resources/wiki/start/topics/tutorials/installoptions/)

Now I use this command to create symlink from correct nginx default path.

```
ln -sf /var/log/nginx/ `2>&1 nginx -V | grep -oP "(?<=--prefix=)\S+"`/logs
```

**Comment by AD7six** [comment]
@rinatio sure, I have no problem with someone creating a PR to update the docs.

**Comment by AD7six** [comment]
I have updated the [getting started docs](https://github.com/h5bp/server-configs-nginx/blob/master/doc/getting-started.md#configure-logs-and-pid-file) to indicate the basics of identifying nginx errors and how to fix them.

Thanks!
