### ISSUE TITLE
fastcgi_params file not included

### ISSUE THREAD

**Issue by ericandrewlewis** [h5bp/server-configs-nginx#107]
I'm using nginx as a web server that hooks up to php-fpm.

I had to copy over the `fastcgi_params` file from the default nginx conf directory. 

Should this be a required step for folks looking to hook nginx to PHP? Can we provide a sensible default set of fastcgi_params, or is that out of the scope of this project's intent?

**Comment by AD7six** [comment]
This overlaps with https://github.com/h5bp/server-configs-nginx/issues/1, I'd rather keep this repo language agnostic, than attempt to cater for everyone's scripting language of choice.

Thanks for the suggestion though.

**Comment by pentago** [comment]
What would be awesome is creating separate H5BP repos with best practices for some of those scripting languages, PHP for instance.. Seems like a good idea to me.

**Comment by ericandrewlewis** [comment]
Perhaps we could [describe this in the Usage guide and link to official documentation](https://github.com/ericandrewlewis/server-configs-nginx/commit/b78c498ba85b76525903c5ab18aceabfad7dc68c)?

**Comment by pentago** [comment]
Official documentation sucks balls as far as I'm concerned.
