### ISSUE TITLE
Externalize configs from nginx.conf

### ISSUE THREAD

**Issue by stanleyxu2005** [h5bp/server-configs-nginx#108]
There is a `conf.d` directory. Better externalize h5bp related configures into a single conf file and put it into `conf.d`.

**Comment by AD7six** [comment]
Generally, conf.d files are included globally - h5bp snippets cannot be included in that way.

> h5bp related configures into a single conf file

There is a [basics](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/basic.conf) file, which contains all the basic ruleset - I don't think it's useful to assume the same setup will work for all users.

Reference: https://github.com/h5bp/server-configs-nginx/issues/13
