### ISSUE TITLE
Add "Public Key Pinning" To Example SSL Config

### ISSUE THREAD

**Issue by quantumpacket** [h5bp/server-configs-nginx#109]
Proposal and discussion on adding the `Public-Key-Pins` header to the `ssl.example.com` file, but have it commented out.

For example:

``` nginx
add_header Public-Key-Pins 'pin-sha256="base64+primary=="; pin-sha256="base64+backup=="; max-age=5184000; includeSubDomains'
```

Reference:
- https://tools.ietf.org/html/rfc7469
- https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning
- https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning

**Comment by quantumpacket** [comment]
Should I submit a PR for this, or close it? It seems nobody is interested in the proposal as it's been up for over 7 months. :frowning:

**Comment by Fequois** [comment]
It's a useful, albeit not very supported, feature. Personally I think it's worth popping a note about HPKP in there. Since it needs "configuration" I guess it should indeed be commented out by default.

**Comment by AD7six** [comment]
@quantumpacket sorry for the silence, I don't close/comment on issues I'm not familiar with.

A PR would be fine

**Comment by quantumpacket** [comment]
@AD7six would this be best put in `ssl.example.com` or in `extra-security.conf`? We already have a CSP header in the latter file, which obviously can't be applied globally to all sites as each site needs a separate policy. I'm guessing people who choose to use CSP are duplicating the file or adding the CSP header in their site config file directly. Since the HPKP header is also per-site, it would probably make sense to do the same to be consistent. What do you think?

Also, since we would be adding HPKP, should we not be adding [HSTS](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) as well? Commented out by default too. All major browsers [support](http://caniuse.com/#feat=stricttransportsecurity) HSTS.

**Comment by quantumpacket** [comment]
@AD7six due to the complexity of properly setting up HPKP and the dangers involved if done wrong (bricking your site until expiration has passed), I'm going to recommend this be closed for now. There are a lot of inherent setup issues with the standard, and with more and more people using Certbot (LetsEncrypt), which makes it difficult to implement HPKP it's probably not wise to provide a means for developer to shoot themselves in the foot. Feel free to re-open if a new implementation standard comes along.
