### ISSUE TITLE
no-transform block may interfere with cache-control headers

### ISSUE THREAD

**Issue by zrisher** [h5bp/server-configs-nginx#11]
Hi everyone,

To my dismay, I realized this week that adding the Cache-Control: No-Transform header in the way specified by the included no-transform.conf:

```
# Prevent mobile network providers from modifying your site
add_header "Cache-Control" "no-transform";
```

can cause your other cache-control values (or their defaults) to malfunction. The nginx docs state:

> Note that for headers other than Last-Modified, it just appends a new header entry to the output header list. So you can't use this directive to rewrite existing headers like Server. Use the headers_more module for it.

This means that the above cache control code actually just adds another Cache-Control line in addition to the default one, which for me was Cache-Control: no-store, no-cache, must-revalidate, etc. Some browsers (Chrome) handled this fine, reading all the values. Others (Safari, Firefox) only read the last line, so ended up seeing no-transform and none of the no-cache directives.

Unfortunately, this seems to mean that if we want full unambiguous control of the cache headers, we must both compile nginx with this custom module AND set our headers in only one place for each location. Has anyone else dealt with this and come up with a better solution?

**Comment by jonathanbell** [comment]
Sorry to butt in on an old conversation here, but I was wondering.. Do we know which mobile providers actually do this? I have yet to see this out in the wild and, as such, do not include "no-transform" in my headers (generally).

**Comment by Malvoz** [comment]
@jonathanbell The `no-transform` cache-control directive not only applies to mobile providers, see this for more info: https://github.com/h5bp/server-configs-apache/issues/185
