### ISSUE TITLE
worker_processes question

### ISSUE THREAD

**Issue by pantocrator27** [h5bp/server-configs-nginx#113]
In https://github.com/h5bp/server-configs-nginx/blob/master/nginx.conf, should worker_processes really be set to 2 by default or auto?  It seems like it would be better to set it to auto by default?  I was just curious as to the rationale of this?

**Comment by Zumochi** [comment]
IMO auto or the number of threads you have.

**Comment by AD7six** [comment]
It was set to a number as at the time [the version this repo used as a minimum didn't accept auto](https://github.com/h5bp/server-configs-nginx/pull/38) - Can be changed now though =).

**Comment by st-isidore-de-seville** [comment]
i have submitted a pull request on the issue.

**Comment by st-isidore-de-seville** [comment]
Many thanks!
