### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by austinpray** [h5bp/server-configs-nginx#115]
Is the current head "stable"?

**Comment by AD7six** [comment]
Master is stable, though you're absolutely right I should release a new version.

If you want to know the differences - they are [mostly comments](https://github.com/h5bp/server-configs-nginx/compare/46312a862a26bf0aa7b75ab605e81ac7b5aa47d6...master) though there are some functional changes.

**Comment by quantumpacket** [comment]
@AD7six new release on the horizon? Also, quite a few PRs that should probably me merged as well.

**Comment by AD7six** [comment]
Yeah .. been quite delayed. Will clean up and make a release today/tomorrow.
