### ISSUE TITLE
http/2 support

### ISSUE THREAD

**Issue by bigandy** [h5bp/server-configs-nginx#117]
Now that nginx 1.9.5 supports http/2 and dumps spdy it would be excellent if there were a default set of http/2 recommended settings.

**Comment by Olvikolvi** [comment]
There is pull request for this.. https://github.com/h5bp/server-configs-nginx/pull/116

**Comment by pentago** [comment]
[#118](https://github.com/h5bp/server-configs-nginx/pull/118)

**Comment by Doniz** [comment]
2016-04-26	
nginx-1.10.0 stable version has been released, incorporating new features from the 1.9.x mainline branch - including the stream module, HTTP/2, dynamic modules support and more.

**Comment by AD7six** [comment]
Closed by https://github.com/h5bp/server-configs-nginx/pull/138

Thanks for asking :)
