### ISSUE TITLE
Reason for static log

### ISSUE THREAD

**Issue by straight-shoota** [h5bp/server-configs-nginx#131]
What is the reason for `access_log logs/static.log;` in [location/expires.conf:14](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf#L14)? I don't see why those files should be logged to a static log - especially since these are usually not static files.

**Comment by franz-josef-kaiser** [comment]
Just hit the wall and wanted to open an issue on that. [link to `expires.conf` blob](https://github.com/h5bp/server-configs-nginx/blob/66d0c463e0a347563692e3df735512b3babdf959/h5bp/location/expires.conf#L14).

First off, I would have expected that the feeds (Atom, RSS, etc.) would have an access log. I can't see any reason why someone would like to keep track of people accessing `manifest appcache html xml json` resources. Before logging that, I'd start logging requests to stand-alone images, css or js to find and block people who abuse an app server as their CDN. 

Aside from that, the path is quite off. In my current example, I am running a Docker container with Nginx. The workdir for Nginx is `/etc/nginx`. That means that the relative path set in `expires.conf` resolves to `/etc/nginx/logs/static.log` while I am logging from all containers to `/var/log/nginx`. That means that the setup breaks.

I'd like to just remove that. If the maintainers agree, I'd like to file a PR. @AD7six opinion?

**Comment by AD7six** [comment]
Sure I don't know why that's there, probably historical.

**Comment by franz-josef-kaiser** [comment]
@AD7six sorry for never sending that PR and thanks for still fixing it :)
