### ISSUE TITLE
expires.conf will break upstream

### ISSUE THREAD

**Issue by bmhm** [h5bp/server-configs-nginx#132]
Hello,

I tried to use the boilerplate with guacamole.
I defined upstream as this:

```
upstream guac {
      server 127.0.0.1:8080;
}
server {
    listen                  443 ssl http2;
    server_name             guac.example.invalid;

    include h5bp/directive-only/ssl.conf;
    include h5bp/directive-only/ssl-stapling.conf;

    # ssl stuff

    rewrite_log on;
    error_log /var/log/nginx/guac.error.log notice;
    access_log /var/log/nginx/guac.access.log main;

    location / {
        access_log              off;
        proxy_pass              http://guac;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        Connection "upgrade";
        proxy_set_header        Proxy-Connection "Keep-Alive";
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;

        proxy_buffering         off;
        proxy_set_header        X-Forwarded-Proto  $scheme;
        proxy_set_header        X-NginX-Proxy  true;
        proxy_http_version 1.1;
    }

    # Include the basic h5bp config set
    #include h5bp/basic.conf;
}
```

However; if I enable the basic.conf, the expires.conf will break guacamole. Because the ~.css|js|jpg etc rules are more specific, they will never be passed to upstream.

Also, this will not work with `try_files $uri @proxy;`.

As the .js files are generated and not directly inside the guacamole .war file, I cannot set a static root.

This means, the basic.conf will break *any* upstream where those files aren't served locally.

**Comment by AD7six** [comment]
This is a general problem with how nginx defines config blocks - there's no rule/location inheritance. Unfortunately that means the files in this repo are not directly usable in many scenarios the one in the issue description being one of them.

See https://github.com/h5bp/server-configs-nginx/blob/master/doc/common-problems.md#only-some-rules-are-being-applied for more information.
