### ISSUE TITLE
Any guide for implementing this?

### ISSUE THREAD

**Issue by canfiax** [h5bp/server-configs-nginx#141]
Are there any tutorials on how to use this github repository? I stumbled upon this repo through this article: https://mattstauffer.co/blog/enabling-gzip-on-nginx-servers-including-laravel-forge

**Comment by AD7six** [comment]
Yes, [there are docs](https://github.com/h5bp/server-configs-nginx#documentation)

If you have a specific question, please create an issue for it as that'll probably indicate missing docs.

Thanks!
