### ISSUE TITLE
Use `always` for security-relevant ´add_header` directives

### ISSUE THREAD

**Issue by leonklingele** [h5bp/server-configs-nginx#147]
```
add_header Adds the specified field to a response header provided that the response
code equals 200, 201, 204, 206, 301, 302, 303, 304, or 307. 
```

For all security-relevant headers you probably want to use the `always` flag, which adds the header regardless of the (upstream) response code.

Examples:
- https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/extra-security.conf (all headers here should use `always`)
- https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf#L40
- https://github.com/h5bp/server-configs-nginx/blob/66d0c463e0a347563692e3df735512b3babdf959/h5bp/directive-only/cross-domain-insecure.conf#L9

**Comment by AD7six** [comment]
Thanks for the PR :+1:
