### ISSUE TITLE
no-default / ssl.no-default don't listen on IPv6

### ISSUE THREAD

**Issue by simonhaenisch** [h5bp/server-configs-nginx#153]
Is there a reason why `sites-available/no-default` and `sites-available/ssl.no-default` don't listen on port 80/443 for IPv6?

I`d suggest to add the line:

``` nginx
listen [::]:80 default_server;
```

and respectively

``` nginx
listen [::]:443 ssl default_server;
```

I haven't tested it, it just came to my mind when going through the config... maybe there is an issue with that?

**Comment by straight-shoota** [comment]
PR #169 fixes this

**Comment by simonhaenisch** [comment]
nice, thank you!
