### ISSUE TITLE
Cache size limit ?

### ISSUE THREAD

**Issue by pascalandy** [h5bp/server-configs-nginx#154]
Hi,

The size a my static web page ([source](https://github.com/firepress-org/splashy/tree/master/www)) is about 220 KBs. Very small and very optimized.

Can we specify in Nginx's config, what is the max cache size ? Let's say 256 KO ? 

Also, which files does Nginx cache in the memory? (HTML, JS, CSS, IMG and scripts)

Cheers!

**Comment by AD7six** [comment]
Please use standard nginx resources to answer questions which are not related to this repo, I'm not sure exactly what your question is about but I refer to [the nginx docs](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_min_length), [nginx .com articles](https://www.nginx.com/blog/nginx-caching-guide/) etc.
