### ISSUE TITLE
robots.txt not accessible?

### ISSUE THREAD

**Issue by hustcer** [h5bp/server-configs-nginx#157]
I know it's easy to fix manually, but I'm wondering why not make robots.txt accessible?

**Comment by AD7six** [comment]
I don't know what this ticket means.

**Comment by hustcer** [comment]
When I use `server-configs-nginx` as the default nginx config, and visite `localhost/robots.txt`, there would be a 404 error. I think we can add `.txt` or `robots.txt` to `expires.conf`, as it's so commonly used, IMO.

**Comment by AD7six** [comment]
There are [no references at all to txt files](https://github.com/h5bp/server-configs-nginx/search?utf8=%E2%9C%93&q=txt) in this repo.

**Comment by hustcer** [comment]
Yes, I know that what do I mean is `maybe you can add the references for txt files or robots.txt in the server-configs-nginx, that way, the other users need not to modify it `.

**Comment by AD7six** [comment]
I can quote myself too :)

> I don't know what this ticket means.

It doesn't help to quote things you've already said, if it meant to me what it means to you - I wouldn't be asking what it means. It _sounds_ (I am guessing because you are not clarifying) like you mean there should be a default response for robots.txt.

**Comment by hustcer** [comment]
Yes, that's what do I mean.
Sorry for my bad English.

**Comment by AD7six** [comment]
ok - that isn't something that belongs here.

`/robots.txt` is part of the _content_ that the webserver is serving. if there is no robots.txt file, it's not part of the webserver's responsibility to invent a response. A default robots.txt file would be, for example, part of the content of the template you use for your web projects.

**Comment by hustcer** [comment]
I mean add something like this:
```
# For something like robots.txt
location ~* \.(?:txt)$ {
  expires 1h;
}
```
to `expires.conf`
