### ISSUE TITLE
Service Worker should not be cached.

### ISSUE THREAD

**Issue by imsus** [h5bp/server-configs-nginx#158]
https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf#L28-L32

Those line block prevents service worker to be refreshed. Usually service worker located in
`root domain` + `/service-worker.js` or `/sw.js`

**Comment by AD7six** [comment]
Please see [the docs](https://github.com/h5bp/server-configs-nginx/blob/master/doc/common-problems.md#only-some-rules-are-being-applied) for some general background.

Please explain your exact config and what you're expeccting/hoping to happen.

**Comment by imsus** [comment]
Hello, @AD7six sorry for not being specific.

So this is actually my problem in production environment where before implementing service worker it works. Then after switching with service worker, the cached file still there. 

What I did was adding the service worker in `location block` inside `sites-available` file like this.

```nginx
location = /service-worker.js {
    expires off;
    add_header Cache-Control no-cache;
    access_log off;
}
```

Since it is specifically my problem. I just share the workaround. Cache Invalidation is hard.

**Comment by AD7six** [comment]
OK.

There's no action to take here though, except to be aware of how nginx works, and prevent scenarios where request match rules you aren't expecting/wanting them to match

**Comment by varnav** [comment]
`Cache-Control: no-cache` actually will not disable cache.
`Cache-Control: no-store` will.
