### ISSUE TITLE
Consider including ssl_dhparam in nginx.conf to stop logjam attack vector

### ISSUE THREAD

**Issue by 121onto** [h5bp/server-configs-nginx#159]
Consider including `ssl_dhparam` in ngnix.conf (possibly commented out).  Also consider including instructions for generating a dhparam.pem file in README.

**Comment by AD7six** [comment]
I don't know much about that directive, PR welcome though.

**Comment by leonklingele** [comment]
This is obsolete and can be closed. Current browsers (Chrome, Firefox, ..) no longer have support for DH(E) cipher suites.

**Comment by leonklingele** [comment]
Well, for backwards-compatibility it might be a good idea though :)

**Comment by AD7six** [comment]
Cool. 👍
