### ISSUE TITLE
Config for download streaming server

### ISSUE THREAD

**Issue by Sarfroz** [h5bp/server-configs-nginx#160]
hello sir can you suggest me what should be the config for nginx if i have dedicated server and users download files from it. we are using stream socket function for downloads not keeping any files on our server.

**Comment by AD7six** [comment]
Hi, this repo isn't meant to be a general Q/A or free server consultation :)

**Comment by Sarfroz** [comment]
do not worry, it took some time but I was able to config something better
than yours.
