### ISSUE TITLE
Error in cache busting config?

### ISSUE THREAD

**Issue by straight-shoota** [h5bp/server-configs-nginx#170]
I haven't tested it, but the replacement in [h5bp/location/cache-busting.conf](https://github.com/h5bp/server-configs-nginx/blob/3270937c3aa4319b0aecd167f57bc1ab7624975b/h5bp/location/cache-busting.conf#L9) looks wrong: `$1.$2` would change `/css/style.20120716.css` to `/css/style.20120716` instead of `/css/style.css`

**Comment by J-Swift** [comment]
The `(?:\d+)` is a non-capturing group, it doesn't get assigned to a variable like the other groups do.

**Comment by stramel** [comment]
Close?
