### ISSUE TITLE
Let's encrypt, .well-known and basic authentication layer

### ISSUE THREAD

**Issue by allantatter** [h5bp/server-configs-nginx#173]
Should something like this to be added globally so Let's Encrypt could access `/.well-known/acme-challenge` even though the site is password protected? Any downsides? I just ran into this problem in real world when requesting a SSL cert from Let's Encrypt and it could not authorize the domain.

```
location /.well-known/acme-challenge {
    auth_basic off;
}
```

**Comment by ianhobbs** [comment]
Anyone else having this problem?

**Comment by tucoinfo** [comment]
I would suggest an agnostic approach. I used to temp unlock password protected sites so as to allow the one time domain verification (not required thereafter so no reason for a permanent fix?). I ended up with an `include` in all my site configs that uses a common `root` for all hosted sites. No more pain. Credits to whoever inspired me at the time.
```
location ^~ /.well-known/acme-challenge/ {
  default_type "text/plain";
  root /usr/local/www/sites/letsencrypt;
  try_files $uri =404;
}
# Hide directory
location = /.well-known/acme-challenge/ {
  return 404;
}
```
I could imagine submitting a PR but there is a need to set `root`.

**Comment by AD7six** [comment]
I don't think the scenario in the ticket description is common enough to warrent any special care. Happy to be proven wrong though.
