### ISSUE TITLE
ssl.conf

### ISSUE THREAD

**Issue by wangjun1801317388** [h5bp/server-configs-nginx#181]
请问怎么没有ssl.conf文件，目前需要配置SSL安全度。

**Comment by hariadi** [comment]
[ssl.conf](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf)

Under `h5bp/directive-only` directory

**Comment by AD7six** [comment]
I think the link in the above comment answers you question :)
