### ISSUE TITLE
Documentation out of date for /docs/usage.md

### ISSUE THREAD

**Issue by andyfry01** [h5bp/server-configs-nginx#189]
Hello!

The [usage docs](https://github.com/h5bp/server-configs-nginx/blob/master/doc/usage.md) specify to git clone the repo with the command:

`git clone git@github.com:h5bp/server-configs-nginx.git nginx`

However, I get this when trying to clone the repo on a Ubuntu 16.04 server:

```
$ git clone git@github.com:h5bp/server-configs-nginx.git nginx
Cloning into 'nginx'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

I'd suggest a small docs update to update that line in [/doc/usage.md](https://github.com/h5bp/server-configs-nginx/blob/master/doc/usage.md) with the command: 

`git clone https://github.com/h5bp/server-configs-nginx.git nginx`

**Comment by LeoColomb** [comment]
Fixed.
