### ISSUE TITLE
remote url content

### ISSUE THREAD

**Issue by Sarfroz** [h5bp/server-configs-nginx#191]
hi, will this configuration of Nginx will be good for creating of remote download URL server. for my use there is no use of database just remote URL download, any config I try creates a heavy cache.
Ex:

>  total        used        free      shared      **# buff/cache**   available
>  Mem:     31G        871M         29G        254M        **# 429M**         29G
>  Swap:    1.0G         39M         #98 4M

buff cache I cleared that's why lower value otherwise it goes more than 2GB.  is there any solution to stop this buff/cache as with apache buff/cache always under 100Mb only. But as I switched to Nginx this buff/cache increased tremendously. Hope you can provide some solutions.

**Comment by LeoColomb** [comment]
> Hope you can provide some solutions.

No, sorry, please contact your host or ask your question on a dedicated forum.
