### ISSUE TITLE
Add GZip compression to woff fonts 

### ISSUE THREAD

**Issue by juan88** [h5bp/server-configs-nginx#198]
More woff fonts are available now and it is not in the default configuration of nginx.

Maybe this is useful for someone else.

 Just add application/font-woff in gzip_types config.

I can add the PR if you want.

Thanks!

**Comment by alrra** [comment]
> Add GZip compression to woff fonts

WOFF files are compressed by default using gzip.

@juan88 See: https://github.com/h5bp/server-configs-apache/issues/42

**Comment by minusf** [comment]
i just wanted to add that some `woff` files are compressed very badly and actually gzipping them makes sense...
