### ISSUE TITLE
TLS v1, TLS v1.1 deprecation

### ISSUE THREAD

**Issue by metalcamp** [h5bp/server-configs-nginx#201]
TLS v1 and v1.1 are deprecated. Why is not ssl.conf (located in server-configs-nginx/h5bp/directive-only) updated accordingly?
`ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;`

**Comment by Niemi** [comment]
repository is still alive?

**Comment by LeoColomb** [comment]
> repository is still alive?

Yes.

> TLS v1 and v1.1 are deprecated

Currently discussed on #190.
