### ISSUE TITLE
The default_server doesn't return 444 if accessing without ssl.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [h5bp/server-configs-nginx#219]
I'm talking about default.conf

If you access it via http://ip:443 (no https), it will not return 444.

How to fix this?

**Comment by LeoColomb** [comment]
To match your custom case, you need to introduce a custom server with the specific listen directives you need.

Also be careful, using port 443 for a non secure HTTP connexion is uncommon and bad practice.

**Comment by gerg5c42g542g2c54g52c** [comment]
> you need to introduce a custom server with the specific listen directives you need

How would one do that?

Doing something like

```
server {
  listen [::]:443 default_server;
  listen 443 default_server;

  server_name _;

  return 444;
}
```

is ignored by nginx: `nginx: [warn] conflicting server name "_" on 0.0.0.0:443, ignored`

**Comment by LeoColomb** [comment]
The nginx output clearly indicates another server is listen on the same port with the same server name. Disable other servers in conflict.

**Comment by gerg5c42g542g2c54g52c** [comment]
Yes, it's the default.conf from this repository.

Even if I remove it and leave just one (without the ssl directive) it will be ignored.

For example, two server directives, one for default_server, one for some domain:

```
server {
  listen [::]:443 default_server;
  listen 443 default_server;

  server_name _;

  return 444;
}
server {
  listen [::]:443 ssl http2;
  listen 443 ssl http2;

  server_name example.com;

  root /;
}
```

This will ignore the example.com vhost. Even if you do `curl example.com` it will result in 444. How would I accomplish this then?

Isn't the point of your default.conf to avoid leaking server info? Because it leaks what's running on the server (anything using ssl will be leaked) if one doesn't know the hostname.
