### ISSUE TITLE
one note for archlinux users

### ISSUE THREAD

**Issue by icf20** [h5bp/server-configs-nginx#223]
https://bugs.archlinux.org/task/46500 

please add a note for arch users to comment line 46 and dont use systemd

**Comment by LeoColomb** [comment]
Thanks for this report, @icf20!
Could you elaborate?

**Comment by emansom** [comment]
Anyone using Arch Linux as distro should be capable of figuring out how to resolve this issue by themselves.

**Comment by LeoColomb** [comment]
I would tend to agree. 😊
Feel free to comment back on this issue of you think a note must be added.
