### ISSUE TITLE
Pagespeed problem (not working anymore)

### ISSUE THREAD

**Issue by Brouskat** [h5bp/server-configs-nginx#225]
Hello,

I started using your nginx config that it look very good but now, my pagespeed module is not working anymore.

Is someone can help me ? I'm pulling my hair with this problem.

Thanks in advance

**Comment by LeoColomb** [comment]
Thanks for opening this report, @Brouskat!

However, the following information are missing to be able to help you:
* Which version of Nginx and module do you use?
* What is the error log and access log output?

**Comment by Brouskat** [comment]
Nginx version 1.15.9 and pagespeed version 1.13.35.2-stable.

I have no errors in my logs about this

**Comment by LeoColomb** [comment]
If you don't have any configuration error neither runtime error, debugging will be difficult...
Be sure that you kept the module enabled and configured as [the documentation recommends](https://www.modpagespeed.com/doc/configuration), and be sure that [`no-transform` is not used](https://github.com/h5bp/server-configs-nginx/blob/fb88c34cde3979354af336e867ecc99ab026284a/h5bp/web_performance/no-transform.conf#L12-L18).

**Comment by Brouskat** [comment]
Yup, the `no-trasnform` was the cause of the problem.

Merci ;)
