### ISSUE TITLE
Where do I load the CSP directive?

### ISSUE THREAD

**Issue by uhlhosting** [h5bp/server-configs-nginx#233]
I tried to load it in nginx.conf file in between the "" it did not helped. Any idea where this should go?

**Comment by LeoColomb** [comment]
> between the ""

What do you mean?

Did you include the [`h5bp/security/content-security-policy.conf`](https://github.com/h5bp/server-configs-nginx/blob/ece9c6b4516833f95e5432b963c77d5bd261adcd/h5bp/security/content-security-policy.conf) file in you server directive?

**Comment by uhlhosting** [comment]
In nginx config there is:

```
  # Add Content-Security-Policy for HTML documents.
  # uhl/security/content-security-policy.conf
  map $sent_http_content_type $content_security_policy {
    ~*text/html "default-src *; script-src *; style-src 'self'; img-src 'self'; font-src *; connect-src *; media-src 'self'; object-src 'self'; child-src 'self'; frame-src$
  }
```

I am not very used with this @variables that are used in 

https://github.com/h5bp/server-configs-nginx/blob/ece9c6b4516833f95e5432b963c77d5bd261adcd/h5bp/security/content-security-policy.conf#L27

**Comment by LeoColomb** [comment]
The map defines conditions and values used when [`h5bp/security/content-security-policy.conf`](https://github.com/h5bp/server-configs-nginx/blob/ece9c6b4516833f95e5432b963c77d5bd261adcd/h5bp/security/content-security-policy.conf) is included. Nothing more. 🙂

**Comment by uhlhosting** [comment]
@LeoColomb so this line: 

  # uhl/security/content-security-policy.conf
Needs to be
 uhl/security/content-security-policy.conf
Inside Nginx.conf

**Comment by LeoColomb** [comment]
@uhlhosting I don't understand your question. And `uhl` is not an existing directory inside `server-configs-nginx` repository.

**Comment by uhlhosting** [comment]
Let's try again I want to enable defaul CSP, what I do?

Do I have to uncomment the # from this in nginx.conf file:

```
  # Add Content-Security-Policy for HTML documents.
  **# uhl/security/content-security-policy.conf**
  map $sent_http_content_type $content_security_policy {
    ~*text/html "default-src *; script-src *; style-src 'self'; img-src 'self'; font-src *; connect-src *; media-src 'self'; object-src 'self'; child-src 'self'; frame-src$
  }
```

**Comment by LeoColomb** [comment]
> there are CSP directives in NGINX.CONF

To be exact, there is a map (which is a consitionnal variable) which define conditions and values for the CSP header addition directive.

But you need to include the CSP header addition directive in your nginx servers.

> Do I have to uncomment the # from this in nginx.conf file

No, you don't have to and even should not.
Set conditions and values only.
```nginx
# Add Content-Security-Policy for HTML documents.
# h5bp/security/content-security-policy.conf
map $sent_http_content_type $content_security_policy {
  regex_condition "value";
}
```
Then, in a server, add the CSP header addition directive.

```nginx
server {
   ...
   include h5bp/security/content-security-policy.conf;
}
```

Hope it's more clear! 🙂
