### ISSUE TITLE
Nginx Amplify Analyzer

### ISSUE THREAD

**Issue by FabianKoestring** [h5bp/server-configs-nginx#234]
Hey there,

i try to optimize my Nginx configuration with this examples. We use Nginx Amplify for monitoring our server. The eanalyzer found following problems...

>### Incomplete or erroneous TLS/SSL configuration
>When ssl, http2, or proxy_protocol parameters are added to a listen directive, they may apply to all listen directives for that port. For example, if you have two virtual servers configured to listen on port 443 and the ssl parameter is set for one of these servers, both servers may be configured for TLS/SSL.
>Check that you haven't accidentally enabled TLS/SSL on a wrong port.

```console
listen *:443 ssl;
listen *:443;
listen *:443 ssl http2;
```

Following line is mentioned:
```console
server {
    ...
    listen 443 ssl http2;
    ...
}
```

Can somebody help me?

**Comment by LeoColomb** [comment]
Thanks for the report @FabianKoestring!

The problem found is about a listen directive inside a server block, so I don't think this is an issue about h5bp templates.

Check that **all** your secure servers are `listen 443 ssl http2;` and/or `listen [::]:443 ssl http2;`.

If it's still erroneous, you'll need to provide all server `listen` directives.
