### ISSUE TITLE
Invalid configuration on CentOS

### ISSUE THREAD

**Issue by ecomsetters** [h5bp/server-configs-nginx#238]
Hi team,
Every configuration file reports as invalid when I test the configuration through NGINX Webserver editor of Virtualmin

![image](https://user-images.githubusercontent.com/42753733/64567075-42511d00-d34f-11e9-891d-f3cf31b438b3.png)

Check the image here.
I tried deleting the first config to see if that was the only one but I get the same error for each and every one.

What am I doing wrong please?

**Comment by LeoColomb** [comment]
Thanks for opening this ticket, @ecomsetters.

You need to contact the support of your host, Virtualmin. We won't be able to help you with their own administration system.
