### ISSUE TITLE
Do you have any 'hotlinking' protection template

### ISSUE THREAD

**Issue by fillon** [h5bp/server-configs-nginx#239]
Hi,

Do you have any template to protect ourself against image 'hotlinking' while still allowing Google/Facebook for example.

Thanks

**Comment by LeoColomb** [comment]
Thanks for opening this, @fillon. 

Yes, hotlink protection has already been discussed, see https://github.com/h5bp/server-configs-nginx/issues/7#issuecomment-43402641
