### ISSUE TITLE
gzip_types missing ttf

### ISSUE THREAD

**Issue by minusf** [h5bp/server-configs-nginx#241]
any particular reason why `font/ttf` is missing from `gzip_types`?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @minusf!

I'm pretty sure you're right as `font/ttf` should be gzip-ed, but do you have some documentation about this?

**Comment by minusf** [comment]
i am afraid nothing besides the numbers...

```
220K    OpenSans-Light.ttf
216K    OpenSans-Regular.ttf
220K    OpenSans-Semibold.ttf
656K    total

116K    OpenSans-Light.ttf.gz
116K    OpenSans-Regular.ttf.gz
120K    OpenSans-Semibold.ttf.gz
352K    total
```

(of course .ttf is not a web optimised font, but that's besides the point)

**Comment by LeoColomb** [comment]
Google Web documentation recommends to compress TTF and EOT: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#reducing_font_size_with_compression

The reason why this mime types [were remove from the list](https://github.com/h5bp/server-configs-nginx/commit/452b63033043031d59eaf1f256b12df50563d246#diff-c08cc45b0285dc9606884cb48de7d259L55) was https://github.com/jshttp/mime-db declarations.
mime-db [update this two months ago](https://github.com/jshttp/mime-db/commit/00e5b32edd0f424cc0cbc32ce999824760ba9864) (https://github.com/jshttp/mime-db/pull/169).

Then we're open to any PR! 🙂

**Comment by minusf** [comment]
i am not sure what is the connection between these two commits to be honest.  what has nginx to do with mime-db?
