### ISSUE TITLE
Content-type header is missing for VTT files

### ISSUE THREAD

**Issue by haggen** [h5bp/server-configs-nginx#243]
Here's the response headers for an VTT file from my nginx server using these config files:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 9334
Content-Security-Policy: default-src https: 'unsafe-inline' 'unsafe-eval'
Date: Tue, 12 Nov 2019 18:50:54 GMT
ETag: "2476-597268df8d680"
Last-Modified: Tue, 12 Nov 2019 13:52:10 GMT
Server: nginx
Strict-Transport-Security: max-age=16070400; preload
X-Content-Type-Options: nosniff
```
But as you can see below VTT types are included.

https://github.com/h5bp/server-configs-nginx/blob/7a44fdf69fe43ef5fe1695bf9ba0376693dab198/mime.types#L136

Most browsers don't seem to care and the subtitle work fine, although the console throws a warning and I read that IE might have issue with it. 

I'm out of gusses why that is though. There's minimal additional configuration, mostly for CSP. No cross origin is happening here.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @haggen.

That we have test suites that validate each mime-type, and it seems vtt files are well defined.

Are you sure your configuration is working well?

**Comment by haggen** [comment]
I think I found what it is. nginx is just a proxy for a local container running apache and I just realized that apache has to report the correct content-type to nginx pick it up. Thanks anyway, I appreciate your help.
