### ISSUE TITLE
Create a h5bp Nginx Dockerfile

### ISSUE THREAD

**Issue by ATLSAPI** [h5bp/server-configs-nginx#255]
The same #42 issue was raised over six years ago. Containerisation and Docker are now more mainstream. Should we consider creating one now?

**Comment by LeoColomb** [comment]
Thanks for raising this, @ATLSAPI.
But please don't duplicate an issue and continue the discussion on the initial one.
What would provide this kind of image instead of doing it manually? How do you manage required customisation?
