### ISSUE TITLE
Intermediate SSL policy docs suggest to use intermediate policy in case

### ISSUE THREAD

**Issue by franz-josef-kaiser** [h5bp/server-configs-nginx#264]
The doc block for the current _intermediate_ SSL policy might need some love:

```
# (!) This policy enforces a strong SSL configuration, which may raise errors
#     with old clients.
#     If a more compatible profile is required, use the intermediate policy.
```

It's not a copy/paste from the other two policies, so I'd assume, it's a typo and `intermediate` might be exchangeable with `deprecated`?

[Link to the current state of doc block](https://github.com/h5bp/server-configs-nginx/blob/18d933c256b27120298475bb7ef90144f39c7d58/h5bp/ssl/policy_intermediate.conf#L10).

**Comment by LeoColomb** [comment]
Thanks for opening this issue @franz-josef-kaiser!
Indeed, really good catch! 👍 
Would you like to open a PR to fix this typo?

**Comment by franz-josef-kaiser** [comment]
@LeoColomb Sure! See reference.
