### ISSUE TITLE
Proxy reverse

### ISSUE THREAD

**Issue by Zonimi** [h5bp/server-configs-nginx#272]
Hello, it would be great if there were recommended settings for reverse proxy. 🙂

As settings for:
- proxy buffers
- proxy cache
- proxy headers

**Comment by LeoColomb** [comment]
Thanks for opening this ticket, @Zonimi.
Could you elaborate and be a bit more specific on what exactly we can recommend as standard for serving web content with these settings?

**Comment by LeoColomb** [comment]
I'm closing the ticket as out of scope and unanswered.
Don't hesitate to continue discussion below.
