### ISSUE TITLE
`X-frame-options: Deny` or `Content-Security-Policy: frame-ancestors none` with Google Search Images

### ISSUE THREAD

**Issue by JulioJu** [h5bp/server-configs-nginx#275]
Hi,

I'm searching sources that said that `X-frame-options: Deny` or `Content-Security-Policy: frame-ancestors none;` on html files could cause problems with Google Search Images, but I don't found. 

https://github.com/h5bp/server-configs-nginx/blob/d249bf2f2bfa51bb6018e73094da6c721ecb0ad1/h5bp/security/x-frame-options.conf#L16-L19 .

Could you give me your source please ?

I don't understand why forbid to embed the website in iframe in another website could cause troubleshooting with Google Images. 

Thanks in advance :-)

**Comment by Dreamsorcerer** [comment]
I feel that maybe someone was mixing up frames and images. Search results would link to the website's images, but it wouldn't embed parts of the page as an iframe...

I suppose the sort of legitimate uses that it was meant to talk might be things more along the lines of overlaid translations or some kind of feature that allows you to annotate over another website, or a presentation tool that displays a web page alongside some additional information in a sidebar, etc.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @JulioJu.
If I remember well, at the time of writing this comment, Google Image Search was actually embeding websites with iframes to allow user to see in-situ image usage.
It's definitely not the case anymore, so probably this ref need to be removed.
Pull-request to fix that? 🙂

**Comment by JulioJu** [comment]
Thanks for your answer 😃 .

Ok I do it 😄
