### ISSUE TITLE
Compress `text/csv` MIME-typed files

### ISSUE THREAD

**Issue by Jcan** [h5bp/server-configs-nginx#276]
Maybe we should add "text/csv" mime-type to compression.conf.

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @Jcan.
Answering this concern is not very easy.
* The list of type that should be compressed is not standard, and "all text-based file-types should be compressed" is a common statement. 
  Following this statement, yes, it should be encrypted.
* But Adding item to the list of compress degrades performance (a little) and CSV is not a type dedicated to web (like HTML, XML, JSON or images).
  Thus, no, it should not be added to the list.

That said, do you have any documentation or material on compressed `text/csv` files for web servers?

**Comment by LeoColomb** [comment]
I'm going to close the issue as undocumented and won't do.
That said please, please, don't hesitate to continue discussion below if you have any material to document the need of CSV files compression.
