### ISSUE TITLE
Mime type audio/x-sid

### ISSUE THREAD

**Issue by midzer** [h5bp/server-configs-nginx#294]
Hi,

how about adding mime type `audio/x-sid` for C64 `.sid` files?

They are in fact text files and might be added to `compression.conf`.

Would be happy to open a PR :)

Have a nice week
midzer

**Comment by LeoColomb** [comment]
Thanks for opening this case @midzer. 😊
That said, there are literally zillion of custom MIME-types and we can't reasonably add all of them in here.
So far, every non-standard MIME type must be motivated with:
* A IANA record of the type;
* A publicly available standard, ideally defining the associated MIME type;
* A description of its value for the web, i.e. is it a file type supposed to be handled by browsers during a web session.

**Comment by midzer** [comment]
Thanks for clarification @LeoColomb :+1: 

There seems to be no defined standard for `.sid` files, informations on the web differ. So, I went ahead and just added this mime type for myself :)

Feel free to close this for good.

**Comment by LeoColomb** [comment]
Alright, thanks for your reply 😊
