### ISSUE TITLE
because it set multiple 'X-Frame-Options' headers

### ISSUE THREAD

**Issue by awmbtc** [h5bp/server-configs-nginx#297]
Refused to display 'https://awmbtc.xyz/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY'). Falling back to 'deny'.

**Comment by quantumpacket** [comment]
@awmbtc Please stop opening new issues for technical support, [read this](https://github.com/h5bp/server-configs-nginx/blob/main/.github/CONTRIBUTING.md#using-the-issue-tracker). You've already been told this by multiple people.
