### ISSUE TITLE
NIST curves (prime256v1, secp384r1, secp521r1): still required to support Microsoft Edge and Safari?

### ISSUE THREAD

**Issue by JackHewson** [h5bp/server-configs-nginx#307]
Do the current versions of Microsoft Edge (with chromium engine) and Safari still require the NIST curves (prime256v1, secp384r1, secp521r1), as mentioned in https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/policy_balanced.conf ?

Or is it "safe" to use https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/policy_strict.conf ?

Thanks!

**Comment by quantumpacket** [comment]
Hi @JackHewson  Please see: https://github.com/h5bp/server-configs-nginx/blob/main/.github/CONTRIBUTING.md#using-the-issue-tracker. If you have a question about a specific option it's best to ask in an alternate channel such as StackOverflow. This  repository is for reporting bugs, feature requests and submitting PRs for the contents within.
