### ISSUE TITLE
CORS but with Origin map for multiple domains

### ISSUE THREAD

**Issue by muuvmuuv** [h5bp/server-configs-nginx#322]
I am really struggling to get this configured but I think with the current cors map it wont work. We have a lot of domains that are only allowed to connect between themself so I would ne mapping of domains that will allow CORS for it, additionally to the resources map already defined here. Is that possible? 

I think this would be a great addition to have a map like this:

```
  map $http_origin $origin_allowed {
    default 0;
    https://domain.app 1;
    https://admin.domain.cloud 1;
    https://domain.cloud 1;
    https://domain.local 1;
    https://localhost:4200 1;
  }
  map $origin_allowed $cors {
    default "";
    1 $http_origin;
  }
```

**Comment by LeoColomb** [comment]
Thanks for opening this issue @muuvmuuv.
You are of course free to configure and tweak H5BP boilerplate to match your use case at its best.
That being said, that would complexity our template too much, and it'd be quite difficult to test.
Also, it's probably much better to enforce CORS usage more at backend level than reverse proxy level.

Anyway, regarding your suggested configuration, that seems to be a correct way to do it with Nginx. If it's not working, I'd recommend to reach out Nginx community.
