### ISSUE TITLE
1.25.2: nginx: [emerg] "location" directive is not allowed here in /etc/nginx/h5bp/location/security_file_access.conf:20

### ISSUE THREAD

**Issue by RichardHausgartner** [h5bp/server-configs-nginx#339]
nginx version: 1.25.2

When running, this error message appears:
`nginx: [emerg] "location" directive is not allowed here in /etc/nginx/h5bp/location/security_file_access.conf:20`

**Comment by ivoba** [comment]
How was this fixed?
I experience this as well.

**Comment by LeoColomb** [comment]
@ivoba `security_file_access.conf` cannot be imported everywhere as it includes `location{}` directives.
It has to be in a proper `server{}` config.

**Comment by ivoba** [comment]
Yep, i had a custom nginx.conf wit a misplaced include.
Using the h5bp nginx.conf it works.
