### ISSUE TITLE
Default config doesn't serve .svgz correctly.

### ISSUE THREAD

**Issue by MatthewMi11er** [h5bp/server-configs-nginx#86]
Using the example site config from latest master version of this repository with nginx 1.4.6 (also tried 1.7) on ubuntu, it does not appear that SVGZ files get served correctly. Firefox gives me an `XML Parsing Error: not well-formed` (Chrome and Safari give similar errors). It appears that the `Content-Encoding gzip` header doesn't get added. Adding something like 
`location ~ \.svgz$ { add_header Content-Encoding gzip;}` seems to make it work. Is there a better way to configure this that could be added to the default config or should a note be made in the docs?

**Comment by AD7six** [comment]
I'm not sure :) will need to investigate.

That might be the right/only solution:

    location ~ \.svgz$ { add_header Content-Encoding gzip;}

Know that if you use that, any [overlapping location blocks](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf#L24-L28) won't apply.

**Comment by 01100001** [comment]
What I don't understand is, why would you serve gzipped files yourself when Nginx does it automatically? Why not just serve SVG and let Nginx do the compression as it does to HTML, CSS, JS, and a bunch of other file types?

(I am asking this as I am curious what the use-case might be.)

**Comment by MatthewMi11er** [comment]
@01100001 SVGZ is a standard format which most svg editors save directly to (some possibly by default). Which means that is sometimes the way designers provide the files.

The overlapping location blocks is no bigger an issue that the current block that handles all the other media types. Note .svgz is included in that media list, making it appear to be supported.

**Comment by jankal** [comment]
The problem with this all svgz stuff is the doubled compression using this config. It first is gz-compressed by the exporting SVG-Editor but then again gz-compressed by nginx. Usually nginx is correctly adding the `Content-Encoding: gzip` header but the browser won't understand cause it only decompresses once and wants a XML file where it again gets a gz-compressed file. So the only solution would be the add this block
````
location ~* \.svgz {
         add_header Content-Encoding "gzip";
}
````
So the header looks like:
````
Content-Encoding: gzip,gzip
````
**Hint: it is not exactly best practice to compress data twice. This often causes an even bigger file than the source.**

**Comment by MatthewMi11er** [comment]
Is there a workable solution that doesn't involve double compressing?

**Comment by jankal** [comment]
This indeed points out a design flaw of the `.svgz` format. According to [W3C ](https://www.w3.org/TR/SVG/intro.html#MIMEType)it also is `image/svg+xml` as a usual `.svg`. So by disabling the compression on `image/svg+xml` the `.svgz` files will be fine. But the usual `.svg` files won't be compressed anymore too. Thats not what we intenionally want. So atm there probably is no right solution cause every existing solution will cause drawbacks.

This brings me to the conclusion: **We need a new MIME-Type!**

**Comment by jankal** [comment]
Something like this also was discussed in h5bp/server-configs-apache#16

**Comment by MatthewMi11er** [comment]
Until that new MIME-Type happens perhaps it would be better to do something like this:

```
location ~* \.svgz {
  #prevent gzipping already gzipped resource.
  gzip off;
  add_header Content-Encoding "gzip";
}
```

**Comment by jankal** [comment]
Yep but with this you again are facing the drawback of 

> any overlapping location blocks won't apply. @AD7six

**Comment by MatthewMi11er** [comment]
The overlapping location blocks is an issue, but it's no different than in the current [expires.conf](https://github.com/h5bp/server-configs-nginx/blob/cb3dc0554eb54ccfab34bfcf32988dfce1872ec2/h5bp/location/expires.conf#L21-L26).
```
# Media: images, icons, video, audio, HTC
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
  expires 1M;
  access_log off;
  add_header Cache-Control "public";
}
```

I suppose this could be handled with some sort of `if` inside that block, but the splitting it into separate location blocks seems better.
