### ISSUE TITLE
SSL Ciphers

### ISSUE THREAD

**Issue by marshallford** [h5bp/server-configs-nginx#91]
I came across a [Hacker News](https://news.ycombinator.com/item?id=9271946) post that linked [to this website](https://cipherli.st/) that lists SSL cipher snippets for all the major web servers. My question is how does the Nginx snippet featured compare to the current ssl.conf used by this repository. Any lines worth bringing over to the ssl configuration? I know very little about SSL ciphers, however I thought would start a conversion on this topic. Thanks to the maintainers of this repository, I really appreciate the work!

**Comment by willfarrell** [comment]
All of the nginx configs mentioned on the site are already covered here plus a few more. With regards to changing the cipher suite. I'm guessing you're thinking "which is it the most secure?", a better question is, "which is the most secure for my users browser?"
While `AES128+EECDH:AES128+EDH` would be a secure cipher suite (at this moment in time), it would be very restrictive on who could connect to your site securely. What is currently documented in https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf is a good balance between strong ciphers and widest user availability (Firefox 1, Chrome 1, IE 7, Opera 5 and Safari 1). Personally I would remove `CAMELLIA` from the list which would prevent `Java 6u45` from accessing your site but would make you site [FIPS 140-2](http://www.carbonwind.net/TLS_Cipher_Suites_Project/tls_ssl_cipher_suites_simple_table_all.htm) compliant. If you don't need to support IE8 you can also remove TLS_RSA_WITH_3DES_EDE_CBC_SHA that doesn't support Forward Secrecy.

If you're worried about your TLS cert run a scan on it. I would recommend [SSLLABS](https://www.ssllabs.com/ssltest/index.html) or [GlobalSign](https://sslcheck.globalsign.com) which uses SSLLabs, but displays results differently.

**Comment by Rowno** [comment]
Also see https://wiki.mozilla.org/Security/Server_Side_TLS and https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by AD7six** [comment]
Closing as I don't see any action to take =).

Also note:

 * [The existing cipher suite is from mozilla's site](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf#L5)
 * [The ssl config generator is mentioned in the docs](https://github.com/h5bp/server-configs-nginx/blob/master/doc/TOC.md#related-projects)

**Comment by marshallford** [comment]
Alright, thanks. The issue was less of "you need to change something" and more of "hey maintainers, take a look at this if you haven't seen it already".

Thanks for a great project, as I always I appreciate the work.
