### ISSUE TITLE
Add ".conf" Extension To Site Config Files

### ISSUE THREAD

**Issue by quantumpacket** [h5bp/server-configs-nginx#95]
Currently the sample site files and the docs say:

> Define host definitions here.
> It'd be a good thing if you keep your hosts indexed by domain name, eg:
> 
> ```
> example.com (handles traffic from both www.example.com and example.com)
> foobar.com (as above)
> test.foobar.com (handles traffic from both www.test.foobar.com and test.foobar.com)
> ```

I agree with that using the domain name in the filename. However, since these files are Nginx config files they should retain that distinction and have a `.conf` extension. Not only for semantic purposes, but also to ensure IDEs will correctly parse the file as the intended filetype. I'm using PhpStorm with Nginx support and my config files are highlighted and checked for errors, but opening a `.com` file will not work.

Since there are essentially countless TLDs that can be used these days. Not enforcing a `.conf` extension will cause a lot of files to be parsed wrongly by IDEs. Take for example the TLD `.py` for Paraguay. Do we really want a dev's IDE to think `example.py` is a Python file?

My proposal is to add the appropriate extension to the sample files and update the documentation. Thoughts?

**Comment by AD7six** [comment]
Well, that's an interesting point, but I don't see IDE usage as a compelling argument. Unlike, say, php files - it's probably much more common for nginx config files to be edited on a server directly than in an IDE. The files in this repo also don't dictate the naming of files for your server either. [There are no sites-enabled files](https://github.com/h5bp/server-configs-nginx/tree/master/sites-enabled) and of [the sites-available files](https://github.com/h5bp/server-configs-nginx/tree/master/sites-available) only no-default is a file that would be used directly.

So, there's nothing stoping you from doing what you ask already, and a change, if there was a change, would only mean.

However, will leave  the issue open for a while to see if any more opinions appear =)

**Comment by StephenBrown2** [comment]
I also prefer having all the site **conf**iguration files end in .conf, as it helps reduce confusion, and lets me use a \*/\*.conf glob to include them, rather than \*/\* which might include files I don't want, say a temporary backup while changes are being tested.

**Comment by AD7six** [comment]
Accounting for tmp files or other noise - that's rather more compelling =)

**Comment by dnixx** [comment]
Absolutely! Every other config file uses the .conf extension, so why wouldn't server block configs?

**Comment by tchalvak** [comment]
Apache 2.4 switched over to requiring .conf at some point in the last few years.  I think it's not too important, but .conf is a good default.

**Comment by ApfelUser** [comment]
I have worked with several different persons and groups on NGINX environments in the past and they **all** always used **.conf**, so I am also going to recommend it.

**Comment by AD7six** [comment]
> I have worked with several different persons and groups on NGINX environments in the past and they all always used .conf

I think that simply depends on your role and the experience of those you've worked with - for example I've never seen anyone use `.conf` for their site config files - and I'm primarily a backend developer.

I did a cursory search for references (these aren't a counter argument, just references) and there are plenty of sources using both techniques here are some using no extension:

[rackspace's docs don't use an extension](http://www.rackspace.com/knowledge_center/article/ubuntu-and-debian-nginx-virtual-hosts#sites-enabled):

> sudo ln -s /etc/nginx/sites-available/domain1.com /etc/nginx/sites-enabled/domain1.com

[digital ocean's docs don't use an extension](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-virtual-hosts-server-blocks-on-ubuntu-12-04-lts--3) (although it :

> sudo ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/example.com

On reflection "noise in the sites-enabled" dir isn't an interesting reason as nobody should be directly editing files in that directory - they are after all only symlinks.

All that said though, this repo is for those who use it, not me alone - so if the consensus of users is that you want to change the [three site files](https://github.com/h5bp/server-configs-nginx/tree/master/sites-available) to have a conf extension - so be it.

**Comment by eric-brechemier** [comment]
I am also generating the config files for each domain, which I name after the domain name, and I never felt the need to add the .conf extension so far.

However, I find the argument of the confusion between TLD and files extension convincing: there is an ambiguity for example between the .md extension for markdown files and the [.md TLD](https://en.wikipedia.org/wiki/.md) for [Republic of Moldova](https://en.wikipedia.org/wiki/Moldova).

I think it makes sense to use the .conf extension consistently in these templates as a best practice.

**Comment by julianxhokaxhiu** [comment]
I was also of the idea to add `.conf` to every file. Although I fixed it by just renaming the symlink in `sites-enabled` folder to `.conf` and editing with my Sublime Text editor from there :)

So I can continue to pull new changes and feel happy to see everything highlighted in my editor.

**Comment by emansom** [comment]
What about `.vhost`?

**Comment by quantumpacket** [comment]
Oh man, completely forgot about this open issue. It's been years! :D

@emansom do you have examples of others using that as an extension? So far `.conf` seems to be the most commonly used, and is even used by Apache. Some of us have brought up using the files in an editor and I don't think (correct me if I am wrong) that `.vhost` is a predefined extension for such files. If that is the case, then it would require additional steps to add it.

**Comment by emansom** [comment]
`.vhost` is used [here](https://github.com/github/linguist/pull/2203) and [there](https://github.com/search?p=1&q=extension%3Avhost+NOT+djdhfidkhfjskdjfkf&ref=searchresults&type=Code&utf8=%E2%9C%93), both for Apache and Nginx virtual host definitions.

**Comment by lenovouser** [comment]
`.conf` is used and distributed by NGINX themselves in their UNIX packages and Docker Images:

 - [**`hg.nginx.org/debian/nginx.vh.default.conf`**](https://hg.nginx.org/pkg-oss/file/tip/debian/nginx.vh.default.conf)
 - [**`github.com/nginx/docker/stable/alpine/nginx.vh.default.conf`**](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/nginx.vh.default.conf)
