### ISSUE TITLE
Debian 8 error - can't start

### ISSUE THREAD

**Issue by DrTrills** [h5bp/server-configs-nginx#98]
Hi all,

Just installed on a debian 8 box in hopes to use with octoberCMS on an upcoming website. when starting nginx I get "Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details."

Here are the results:

```
$ systemctl status nginx.service
    ● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: failed (Result: exit-code) since Fri 2015-05-15 23:16:15 EDT; 2min 18s ago
  Process: 16115 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status=0/SUCCESS)
  Process: 15542 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=0/SUCCESS)
  Process: 16168 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
 Main PID: 4135 (code=exited, status=0/SUCCESS)
```

not sure where to go from here- will post an update if I find a solution.

**Comment by AD7six** [comment]
This doesn't look to have anything to do with this repo. Are you using this nginx config file?

There are instructions to read the logs in the error output. Alternatively, a simple way to see a startup problem is to run nginx in the foreground:

    nginx -c /etc/nginx/nginx.conf -t

Or similar.

**Comment by AD7six** [comment]
Closing as there's no more info, and this doesn't look to be related to this repo directly.

**Comment by b0jan** [comment]
Had the same issue when applied this nginx config. 
- Make sure www user and www group exists.
- In my case nginx log files coudn't be created, after fixing that check error.log for all erros and it should be really straightforward to fix other issues.
